// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqLNcMmAOfAcc7tDkWfYV2tYdhlNPWdVE',
    appId: '1:48521901983:web:95d62c28bc2e73b857afaa',
    messagingSenderId: '48521901983',
    projectId: 'bus-book-2',
    authDomain: 'bus-book-2.firebaseapp.com',
    storageBucket: 'bus-book-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7fNHp575auik5xdIut_C0lST3Z_W6u4',
    appId: '1:48521901983:android:322f1bdc17811f5157afaa',
    messagingSenderId: '48521901983',
    projectId: 'bus-book-2',
    storageBucket: 'bus-book-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Id1WUSZA5jKdoTeAWgCc9441BcpVpE8',
    appId: '1:48521901983:ios:42f4045ae183049957afaa',
    messagingSenderId: '48521901983',
    projectId: 'bus-book-2',
    storageBucket: 'bus-book-2.firebasestorage.app',
    iosBundleId: 'com.example.busBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeywmxH13HJMxrI5B2ssVucsLww300ZK0',
    appId: '1:39653739164:ios:d54a17e72fb0852ee43b59',
    messagingSenderId: '39653739164',
    projectId: 'bus-book-d14ef',
    storageBucket: 'bus-book-d14ef.firebasestorage.app',
    iosBundleId: 'com.example.busBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTmOCIgjXCGsJ7DxZ6AN19karJU8Aa5MM',
    appId: '1:39653739164:web:e18b73720fc8fa9ce43b59',
    messagingSenderId: '39653739164',
    projectId: 'bus-book-d14ef',
    authDomain: 'bus-book-d14ef.firebaseapp.com',
    storageBucket: 'bus-book-d14ef.firebasestorage.app',
    measurementId: 'G-GRZQTQKCYV',
  );
}